// <auto-generated />
using System;
using Bloodhound.Core.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bloodhound.Core.Migrations
{
    [DbContext(typeof(BloodhoundContext))]
    [Migration("20200207014538_v-OffenderLastLocations")]
    partial class vOffenderLastLocations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
