//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bloodhound.Core.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TimeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bloodhound.Core.App_LocalResources.TimeResources", typeof(TimeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        internal static string Time_DaysFormat {
            get {
                return ResourceManager.GetString("Time_DaysFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day ago.
        /// </summary>
        internal static string Time_DaySingular {
            get {
                return ResourceManager.GetString("Time_DaySingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        internal static string Time_HoursFormat {
            get {
                return ResourceManager.GetString("Time_HoursFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour ago.
        /// </summary>
        internal static string Time_HourSingular {
            get {
                return ResourceManager.GetString("Time_HourSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        internal static string Time_MinutesFormat {
            get {
                return ResourceManager.GetString("Time_MinutesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moments ago.
        /// </summary>
        internal static string Time_MinuteSingular {
            get {
                return ResourceManager.GetString("Time_MinuteSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        internal static string Time_MonthsFormat {
            get {
                return ResourceManager.GetString("Time_MonthsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 month ago.
        /// </summary>
        internal static string Time_MonthSingular {
            get {
                return ResourceManager.GetString("Time_MonthSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years ago.
        /// </summary>
        internal static string Time_YearsFormat {
            get {
                return ResourceManager.GetString("Time_YearsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 year ago.
        /// </summary>
        internal static string Time_YearSingular {
            get {
                return ResourceManager.GetString("Time_YearSingular", resourceCulture);
            }
        }
    }
}
